# Generated by Django 5.1.3 on 2024-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
