# Generated by Django 5.1.3 on 2024-11-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='no description provided', max_length=250),
        ),
    ]
